# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nakebli <nakebli@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/20 16:00:17 by nakebli           #+#    #+#              #
#    Updated: 2023/09/20 16:57:07 by nakebli          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = megaphone
SRCS = megaphone.cpp
FLAGS = -Wall -Wextra -Werror
all: $(NAME)

$(NAME):
	c++ $(FLAGS) megaphone.cpp -o megaphone

clean:
	rm -rf $(NAME)